[package]
name = "weather-tui"
version = "0.1.0"
edition = "2021"
description = "Weather in the terminal."
documentation = "https://github.com/Xithrius/weather-tui"
homepage = "https://github.com/Xithrius/weather-tui"
repository = "https://github.com/Xithrius/weather-tui"
license = "MIT OR Apache-2.0"
keywords = ["tui", "weather"]
categories = ["command-line-utilities"]

[dependencies]
tui = { version = "0.18.0", default-features = false, features = [ "crossterm" ] }
serde = { version = "1.0.136", features = [ "derive" ] }
clap = { version = "3.2.13", features = [ "derive", "cargo" ] }
tokio = { version = "1.20.1", features = [ "full" ] }
crossterm = "0.24.0"
serde_json = "1.0.82"
toml = "0.5.8"
color-eyre = "0.6.1"
unicode-width = "0.1.9"
unicode-segmentation = "1.9.0"
chrono = "0.4"
rustyline = "10.0.0"
log = "0.4.17"
fern = "0.6.1"

[profile.dev.package.backtrace]
opt-level = 3

[[bin]]
bench = false
path = "src/main.rs"
name = "wt"

[profile.release]
lto = "thin"
