[terminal]
# How often the terminal will update
tick_delay = 30

[weather]
# The key to acquire weather information with
api_key = ""
# The area in which the user would like weather data from
area = ""

[frontend]
# The margin around the main window from to the terminal border
margin = 0
